export default [
    {
        id: 1,
        name: "Люси",
        icons: {
            regular: 'svg',
            smirk: 'svg',
            smile: 'svg',
            regular2: 'svg',
            smirk2: 'svg',
            smile2: 'svg',
            full: 'svg',
        },
    },
    {
        id: 2,
        name: "PR менеджер",
        icons: {
            call: 'svg',
            wink_coffee: 'svg',
            full_chart: 'svg',
            full_out: 'svg',
            hug_request: 'svg',
            pie_chart: 'svg',
            regular_book: 'svg',
            regular_phone: 'svg',
            smile: 'svg',
            smile_greetings: 'svg',
            tired: 'svg',
        },
    },
    {
        id: 3,
        name: "Премьер",
        icons: {
            big_smile: 'svg',
            blind_small_smile: 'svg',
            full_hug: 'svg',
            full_regular: 'svg',
            hands_up: 'svg',
            regular: 'svg',
            regular_phone: 'svg',
            report: 'svg',
            report_smile: 'svg',
            small_smile: 'svg',
            speech: 'svg',
            wink: 'svg',
        },
    },
    {
        id: 4,
        name: "Министр ВС",
        icons: {
            call: 'svg',
            chart: 'svg',
            coffee: 'svg',
            full_bag: 'svg',
            full_regular: 'svg',
            hands_up: 'svg',
            interes: 'svg',
            panic: 'svg',
            regular: 'svg',
            regular2: 'svg',
            speech: 'svg',
        },
    },
    {
        id: 5,
        name: "Дочь Галчонок",
        icons: {
            call: 'svg',
            closed_eyes: 'svg',
            full_regular: 'svg',
            greetings: 'svg',
            idea: 'svg',
            like: 'svg',
            phone_scrolling: 'svg',
            regular: 'svg',
            smile: 'svg',
            smile_call: 'svg',
            super: 'svg',
            wink: 'svg',
        },
    },
    {
        id: 6,
        name: "Министр здравоохранения",
        icons: {
            full_out: 'svg',
            full_regular: 'svg',
            full_speach: 'svg',
            regular: 'svg',
            sad: 'svg',
            small_report: 'svg',
            small_speech2: 'svg',
            speech: 'svg',
            stress: 'svg',
        },
    },
    {
        id: 7,
        name: "Посол",
        icons: {
            call: 'svg',
            cash: 'svg',
            fear: 'svg',
            frendly: 'svg',
            full_fear: 'svg',
            full_regular: 'svg',
            full_speech: 'svg',
            full_superman: 'svg',
            hands_on_ears: 'svg',
            happy: 'svg',
            regular: 'svg',
            regular_coffee: 'svg',
            regular_folder: 'svg',
            speech: 'svg',
            superman: 'svg',
        },
    },
    {
        id: 8,
        name: "Министр финансов",
        icons: {
            angry: 'svg',
            cash: 'svg',
            desk_coffee: 'svg',
            desk_fear: 'svg',
            desk_greetings: 'svg',
            full_chart_down: 'svg',
            full_regular: 'svg',
            meditation: 'svg',
            regular: 'svg',
            rocket_happy: 'svg',
            smile: 'svg',
            untrust_chart: 'svg',
            win_maraphone: 'svg',
        },
    },
    {
        id: 9,
        name: "Ученный",
        icons: {
            notebook: 'svg',
            full_regular: 'svg',
            sit: 'svg',
            regular: 'svg',
            hands_up: 'svg',
            full_speach: 'svg',
            full_out: 'svg',
            call: 'svg',
            full_superman: 'svg',
            wink: 'svg',
            without_glasses: 'svg',
            superman: 'svg',
            think: 'svg',
            speech: 'svg',
            fear: 'svg',
            angry: 'svg',
        },
    },
    {
        id: 10,
        name: "Глава МЧС",
        icons: {
            angry: 'svg',
            full_back: 'svg',
            full_regular: 'svg',
            oops: 'svg',
            regular: 'svg',
            sad: 'svg',
            smile: 'svg',
        },
    },
]